name: Release
on:
  release:
    types:
      - released
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write

jobs:
  publish:
    uses: cthulhu-oidc/workflows/.github/workflows/release.yml@master
    with:
      git-tag: ${{ github.event.release.tag_name }}
      branch:  ${{ github.event.release.target_commitish }}
    secrets: inherit
