name: "Handle stale issues and pull-requests"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      closeStale:
        description: 'Close stale'     
        required: false
        type: boolean
        default: true
      lockStale:
        description: 'Lock stale'     
        required: false
        type: boolean
        default: true

jobs:
  stale:
    uses: cthulhu-oidc/workflows/.github/workflows/stale.yml@master
    with:
      closeStale: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.closeStale == 'true') || github.event_name != 'workflow_dispatch' }}
      lockStale: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.lockStale == 'true') || github.event_name != 'workflow_dispatch' }}
